### ISSUE TITLE
Firebase API key & secret in plaintext

### ISSUE THREAD

**Issue by mooncos** [hackclub/shipit#12]
`apiKey` param **clearly visible** to anyone in [app.js](https://github.com/mj66/shipit/blob/master/asset/js/app.js)

https://github.com/mj66/shipit/blob/620242ec2d6f020f487e2ee5ab248b5862380e62/asset/js/app.js#L3

This is a **critical** security issue and should be addressed asap. Some solutions involve fetching `apiKey` from a separate gitignored file or from an `env var`.

**Comment by itsmingjie** [comment]
Hmm... I interesting...

So I looked up the risk of exposing Firebase API Key, and I found that storing API key in front-end is not a security risk, ask Firebase will need an authorized domain in order to run. Therefore, just having the API key is not a security risk to the database, especially when we have strict i/o rules set up for the database.

Ref: [StackOverflow](https://stackoverflow.com/questions/37482366/is-it-safe-to-expose-firebase-apikey-to-the-public)

**Comment by mooncos** [comment]
Ah ok, I thought that there weren’t any domain auth, restrictions or rules. I was just advising of a coming convention in OSS development.
Thanks for the insight.
